print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/shahzebkhalid/Documents/Computer-Game-Design /2.5D Game/2.5D Game /Assets/Prefabs/3DZombieAssets/models/Maya/3DPlatform.ma"`)
{		
	file -o "/Users/shahzebkhalid/Documents/Computer-Game-Design /2.5D Game/2.5D Game /Assets/Prefabs/3DZombieAssets/models/Maya/3DPlatform.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/shahzebkhalid/Documents/Computer-Game-Design /2.5D Game/2.5D Game /Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/shahzebkhalid/Documents/Computer-Game-Design /2.5D Game/2.5D Game /Temp/CommandPipe";

$donepipeKill = `fopen "/Users/shahzebkhalid/Documents/Computer-Game-Design /2.5D Game/2.5D Game /Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
